### ISSUE TITLE
Implement Synonym Tokenizer

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum_elastic#5]
As a user
I would like suggestions (phrase suggester) in search
because I sometimes make mistakes in my spelling

Just chemicals, preferred name

**Comment by mwfrost** [comment]
This ticket was further specified at our in-person meeting and in subsequent conversations. The goal now is to allow the `dashboard` index to return results when the search term is a synonym of the actual chemical name. So searching for "water" will return records where the chemical name is "H2O" or "aqua" or "eau", etc.

Then it became apparent that we do not have a ready-to-use master list of synonyms, so we have decided to call the ticket complete when the application can read a sample set of synonyms from a file stored in version control.
